# Generated by Django 4.2.30 on 2026-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_categoria_created_at_categoria_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
