# Generated by Django 4.2.30 on 2026-05-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_imagen_url_receta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='duracion',
            new_name='elaboracion',
        ),
    ]
