# Generated by Django 4.2.30 on 2026-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_rename_duracion_receta_elaboracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='pasos',
            field=models.JSONField(default=list),
        ),
    ]
