# Generated by Django 4.2.30 on 2026-05-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_receta_pasos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='pasos',
            new_name='ingredientes',
        ),
    ]
