# Generated by Django 4.2.30 on 2026-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_rename_pasos_receta_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='raciones',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_de_elaboracion',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='elaboracion',
            field=models.JSONField(default=list),
        ),
    ]
