# Generated by Django 4.2.30 on 2026-05-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interacciones', '0001_initial'),
        ('recetas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes_emitidos', to='usuarios.usuario')),
                ('usuario_sancionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes_recibidos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Strike Log',
                'verbose_name_plural': 'Strike Logs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='interacciones.comentario')),
                ('informador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to='usuarios.usuario')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
