# Generated by Django 4.2.30 on 2026-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='strikelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='strikelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
